package fr.univrouen.stb23v1.model;

import jakarta.persistence.*;
import jakarta.xml.bind.annotation.*;

import jakarta.persistence.Id;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "Client")
@XmlType(propOrder = {"entity", "person", "mail", "tel"})
@XmlAccessorType(XmlAccessType.FIELD)
public class Client {

    /**
     * Autogenerated id.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlTransient
    private Integer id;

    /**
     * Person 1-1 element.
     */
    @XmlElement
    @OneToOne(cascade=CascadeType.ALL)
    @JoinColumn(name = "personId")
    private Person person;

    /**
     * Client entity name.
     */
    @XmlElement
    private String entity;

    /**
     * Client mails list.
     */
    @XmlElement
    private List<String> mail = new ArrayList<>();

    /**
     * Client tels list.
     */
    @XmlElement
    private List<String> tel = new ArrayList<>();

    public Client() {
    }

    /**
     * @return The client id.
     */
    public Integer getId() {
        return id;
    }

    /**
     * @return The client 1-1 person.
     */
    public Person getPerson() {
        return person;
    }

    /**
     * @return The client entity name.
     */
    public String getEntity() {
        return entity;
    }

    /**
     * @return The client mails list.
     */
    public List<String> getMail() {
        return mail;
    }

    /**
     * @return The client tels list.
     */
    public List<String> getTel() {
        return tel;
    }

}
