package fr.univrouen.stb23v1.model;

import jakarta.persistence.*;
import jakarta.xml.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "Features")
@XmlAccessorType(XmlAccessType.FIELD)
public class Features {

    /**
     * Autogenerated id.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlTransient
    private Integer id = 1;

    /**
     * Features list.
     */
    @XmlElement
    @OneToMany(targetEntity=Feature.class, cascade=CascadeType.ALL)
    private List<Feature> feature = new ArrayList<>();

    public Features() {
    }

    /**
     * @return The features id.
     */
    public Integer getId() {
        return id;
    }

    /**
     * @return The features list.
     */
    public List<Feature> getFeature() {
        return feature;
    }

}
