package fr.univrouen.stb23v1.model;

import jakarta.persistence.*;
import jakarta.xml.bind.annotation.*;

@Entity
@Table(name = "Feature")
@XmlType(propOrder = {"description", "priority", "delivery", "comment"})
@XmlAccessorType(XmlAccessType.FIELD)
public class Feature {

    /**
     * Autogenerated id.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlTransient
    private Integer id;

    /**
     * Feature name (attribute).
     */
    @XmlAttribute
    private String name;

    /**
     * Feature section (attribute).
     */
    @XmlAttribute
    private Integer section;

    /**
     * Feature number (attribute).
     */
    @XmlAttribute
    private Integer number;

    /**
     * Feature description.
     */
    @XmlElement
    private String description;

    /**
     * Feature priority.
     */
    @XmlElement
    private Integer priority;

    /**
     * Feature delivery date.
     */
    @XmlElement
    private String delivery;

    /**
     * Feature additional comment.
     */
    @XmlElement
    private String comment;

    public Feature() {
    }

    /**
     * @return The feature id.
     */
    public Integer getId() {
        return id;
    }

    /**
     * @return The feature name attribute.
     */
    public String getName() {
        return name;
    }

    /**
     * @return The feature section attribute.
     */
    public Integer getSection() {
        return section;
    }

    /**
     * @return The feature number attribute.
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * @return The feature description.
     */
    public String getDescription() {
        return description;
    }

    /**
     * @return The feature priority.
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * @return The feature delivery date.
     */
    public String getDelivery() {
        return delivery;
    }

    /**
     * @return The feature additional comment.
     */
    public String getComment() {
        return comment;
    }

}
