package fr.univrouen.stb23v1.model;

import jakarta.persistence.*;
import jakarta.xml.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "Member")
@XmlType(propOrder = {"person", "mail", "function"})
@XmlAccessorType(XmlAccessType.FIELD)
public class Member {

    /**
     * Autogenerated id.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlTransient
    private Integer id;

    /**
     * The 1-1 person.
     */
    @XmlElement
    @OneToOne(cascade=CascadeType.ALL)
    @JoinColumn(name = "personId")
    private Person person;

    /**
     * The member mail.
     */
    @XmlElement
    private String mail;

    /**
     * The functions handled.
     */
    @XmlElement
    private List<String> function = new ArrayList<>();

    public Member() {
    }

    /**
     * @return The member id.
     */
    public Integer getId() {
        return id;
    }

    /**
     * @return The 1-1 person.
     */
    public Person getPerson() {
        return person;
    }

    /**
     * @return The member mail.
     */
    public String getMail() {
        return mail;
    }

    /**
     * @return The functions handled.
     */
    public List<String> getFunction() {
        return function;
    }

}
