package fr.univrouen.stb23v1.model;

import jakarta.persistence.*;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlTransient;
import jakarta.xml.bind.annotation.XmlValue;

@Entity
@Table(name = "Person")
public class Person {

    /**
     * Autogenerated id.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlTransient
    private Integer id;

    /**
     * The person name.
     */
    @XmlValue
    private String name;

    /**
     * The person gender (attribute).
     */
    @XmlAttribute
    private String gender;

    /**
     * The person last name (attribute).
     */
    @XmlAttribute
    private String lastname;

    public Person() {
    }

    /**
     * @return The person id.
     */
    public Integer getId() {
        return id;
    }

    /**
     * @return The person name.
     */
    public String getName() {
        return name;
    }

    /**
     * @return The person gender.
     */
    public String getGender() {
        return gender;
    }

    /**
     * @return The person last name.
     */
    public String getLastname() {
        return lastname;
    }

}
